const makes = [
  { value: 51539, label: '9ff' },
  { value: 16396, label: 'Abarth' },
  { value: 14979, label: 'AC' },
  { value: 16429, label: 'ACM' },
  { value: 16356, label: 'Acura' },
  { value: 51872, label: 'Aiways' },
  { value: 16352, label: 'Aixam' },
  { value: 51917, label: 'Alba Mobility' },
  { value: 6, label: 'Alfa Romeo' },
  { value: 14, label: 'Alpina' },
  { value: 51796, label: 'Alpine' },
  { value: 51545, label: 'Amphicar' },
  { value: 51918, label: 'Angelelli Automobili' },
  { value: 16419, label: 'Ariel Motor' },
  { value: 16427, label: 'Artega' },
  { value: 51948, label: 'Aspark' },
  { value: 16431, label: 'Aspid' },
  { value: 8, label: 'Aston Martin' },
  { value: 9, label: 'Audi' },
  { value: 51929, label: 'Aurus' },
  { value: 15643, label: 'Austin' },
  { value: 51901, label: 'Austin-Healey' },
  { value: 15644, label: 'Autobianchi' },
  { value: 51774, label: 'BAIC' },
  { value: 16400, label: 'Bedford' },
  { value: 16416, label: 'Bellier' },
  { value: 11, label: 'Bentley' },
  { value: 52007, label: 'Bestune' },
  { value: 13, label: 'BMW' },
  { value: 51900, label: 'Boldmen' },
  { value: 16418, label: 'Bolloré' },
  { value: 16424, label: 'Borgward' },
  { value: 16367, label: 'Brilliance' },
  { value: 51895, label: 'Bristol' },
  { value: 51986, label: 'Brute' },
  { value: 15, label: 'Bugatti' },
  { value: 16, label: 'Buick' },
  { value: 16379, label: 'BYD' },
  { value: 17, label: 'Cadillac' },
  { value: 15672, label: 'Caravans-Wohnm' },
  { value: 51912, label: 'Carver' },
  { value: 16407, label: 'Casalini' },
  { value: 16335, label: 'Caterham' },
  { value: 51936, label: 'Cenntro' },
  { value: 16401, label: 'Changhe' },
  { value: 16357, label: 'Chatenet' },
  { value: 16384, label: 'Chery' },
  { value: 19, label: 'Chevrolet' },
  { value: 20, label: 'Chrysler' },
  { value: 51971, label: 'Cirelli' },
  { value: 21, label: 'Citroen' },
  { value: 16411, label: 'CityEL' },
  { value: 16380, label: 'Corvette' },
  { value: 51802, label: 'CUPRA' },
  { value: 16360, label: 'Dacia' },
  { value: 22, label: 'Daewoo' },
  { value: 16333, label: 'DAF' },
  { value: 23, label: 'Daihatsu' },
  { value: 16397, label: 'Daimler' },
  { value: 51947, label: 'Dallara' },
  { value: 16434, label: 'Dangel' },
  { value: 16423, label: 'De la Chapelle' },
  { value: 51779, label: 'De Tomaso' },
  { value: 51859, label: 'Delorean' },
  { value: 51920, label: 'Devinci Cars' },
  { value: 51773, label: 'DFSK' },
  { value: 2152, label: 'Dodge' },
  { value: 16339, label: 'Donkervoort' },
  { value: 16383, label: 'DR Automobiles' },
  { value: 16415, label: 'DS Automobiles' },
  { value: 51552, label: 'Dutton' },
  { value: 51794, label: 'e.GO' },
  { value: 52008, label: 'Ebro' },
  { value: 51835, label: 'Econelo' },
  { value: 51905, label: 'Edran' },
  { value: 51880, label: 'Elaris' },
  { value: 51874, label: 'Embuggy' },
  { value: 51924, label: 'EMC' },
  { value: 16436, label: 'Estrima' },
  { value: 51919, label: 'Evetta' },
  { value: 51831, label: 'EVO' },
  { value: 27, label: 'Ferrari' },
  { value: 28, label: 'Fiat' },
  { value: 51543, label: 'FISKER' },
  { value: 29, label: 'Ford' },
  { value: 51987, label: 'Forthing' },
  { value: 51973, label: 'Foton' },
  { value: 51542, label: 'Gac Gonow' },
  { value: 16337, label: 'Galloper' },
  { value: 51907, label: 'Gappy' },
  { value: 16386, label: 'GAZ' },
  { value: 16403, label: 'GEM' },
  { value: 51540, label: 'GEMBALLA' },
  { value: 51885, label: 'Genesis' },
  { value: 51837, label: 'Giana' },
  { value: 51791, label: 'Gillet' },
  { value: 16421, label: 'Giotti Victoria' },
  { value: 2153, label: 'GMC' },
  { value: 51813, label: 'Goupil' },
  { value: 16382, label: 'Great Wall' },
  { value: 16409, label: 'Grecav' },
  { value: 51926, label: 'GTA' },
  { value: 51981, label: 'GWM' },
  { value: 51512, label: 'Haima' },
  { value: 51534, label: 'Hamann' },
  { value: 51816, label: 'Haval' },
  { value: 51977, label: 'Hiphi' },
  { value: 51881, label: 'Holden' },
  { value: 31, label: 'Honda' },
  { value: 51988, label: 'Hongqi' },
  { value: 15674, label: 'HUMMER' },
  { value: 51767, label: 'Hurtan' },
  { value: 33, label: 'Hyundai' },
  { value: 51992, label: 'ICH-X' },
  { value: 51925, label: 'Ineos' },
  { value: 16355, label: 'Infiniti' },
  { value: 15629, label: 'Innocenti' },
  { value: 52006, label: 'Invicta' },
  { value: 16402, label: 'Iso Rivolta' },
  { value: 35, label: 'Isuzu' },
  { value: 14882, label: 'Iveco' },
  { value: 16387, label: 'IZH' },
  { value: 51849, label: 'JAC' },
  { value: 51999, label: 'Jaecoo' },
  { value: 37, label: 'Jaguar' },
  { value: 38, label: 'Jeep' },
  { value: 51910, label: 'Jensen' },
  { value: 51875, label: 'Karma' },
  { value: 51975, label: 'KG Mobility' },
  { value: 39, label: 'Kia' },
  { value: 51781, label: 'Koenigsegg' },
  { value: 50060, label: 'KTM' },
  { value: 40, label: 'Lada' },
  { value: 41, label: 'Lamborghini' },
  { value: 42, label: 'Lancia' },
  { value: 15641, label: 'Land Rover' },
  { value: 16426, label: 'LDV' },
  { value: 52000, label: 'Leapmotor' },
  { value: 51854, label: 'LEVC' },
  { value: 43, label: 'Lexus' },
  { value: 16393, label: 'Lifan' },
  { value: 16353, label: 'Ligier' },
  { value: 14890, label: 'Lincoln' },
  { value: 51883, label: 'Linzda' },
  { value: 52003, label: 'Livan' },
  { value: 51908, label: 'Lorinser' },
  { value: 44, label: 'Lotus' },
  { value: 51921, label: 'Lucid' },
  { value: 51914, label: 'Lynk & Co' },
  { value: 51976, label: 'M-Ero' },
  { value: 16359, label: 'Mahindra' },
  { value: 51780, label: 'MAN' },
  { value: 16435, label: 'Mansory' },
  { value: 51906, label: 'Martin' },
  { value: 16410, label: 'Martin Motors' },
  { value: 45, label: 'Maserati' },
  { value: 51955, label: 'Matra' },
  { value: 51803, label: 'Maxus' },
  { value: 16348, label: 'Maybach' },
  { value: 46, label: 'Mazda' },
  { value: 51519, label: 'McLaren' },
  { value: 51902, label: 'Mega' },
  { value: 16399, label: 'Melex' },
  { value: 47, label: 'Mercedes-Benz' },
  { value: 51834, label: 'Mercury' },
  { value: 48, label: 'MG' },
  { value: 51965, label: 'Micro' },
  { value: 16361, label: 'Microcar' },
  { value: 51897, label: 'Militem' },
  { value: 51903, label: 'Minari' },
  { value: 51766, label: 'Minauto' },
  { value: 16338, label: 'MINI' },
  { value: 50, label: 'Mitsubishi' },
  { value: 51782, label: 'Mitsuoka' },
  { value: 52004, label: 'Mobilize' },
  { value: 51, label: 'Morgan' },
  { value: 16388, label: 'Moskvich' },
  { value: 51554, label: 'MP Lafer' },
  { value: 51788, label: 'MPM Motors' },
  { value: 51928, label: 'NIO' },
  { value: 52, label: 'Nissan' },
  { value: 50111, label: 'NSU' },
  { value: 53, label: 'Oldsmobile' },
  { value: 15670, label: 'Oldtimer' },
  { value: 51991, label: 'Omoda' },
  { value: 54, label: 'Opel' },
  { value: 51934, label: 'Ora' },
  { value: 16341, label: 'Pagani' },
  { value: 51553, label: 'Panther Westwinds' },
  { value: 55, label: 'Peugeot' },
  { value: 50083, label: 'PGO' },
  { value: 16350, label: 'Piaggio' },
  { value: 51770, label: 'Plymouth' },
  { value: 51817, label: 'Polestar' },
  { value: 56, label: 'Pontiac' },
  { value: 57, label: 'Porsche' },
  { value: 15636, label: 'Proton' },
  { value: 15646, label: 'Puch' },
  { value: 51793, label: 'RAM' },
  { value: 51812, label: 'Regis' },
  { value: 16398, label: 'Reliant' },
  { value: 60, label: 'Renault' },
  { value: 61, label: 'Rolls-Royce' },
  { value: 62, label: 'Rover' },
  { value: 51536, label: 'Ruf' },
  { value: 63, label: 'Saab' },
  { value: 16369, label: 'Santana' },
  { value: 64, label: 'SEAT' },
  { value: 51866, label: 'Segway' },
  { value: 51839, label: 'Selvo' },
  { value: 51861, label: 'Seres' },
  { value: 51827, label: 'Sevic' },
  { value: 51913, label: 'SGS' },
  { value: 51896, label: 'Shelby' },
  { value: 51800, label: 'Shuanghuan' },
  { value: 51853, label: 'Silence' },
  { value: 51909, label: 'Singer' },
  { value: 65, label: 'Skoda' },
  { value: 51959, label: 'Skywell' },
  { value: 15525, label: 'smart' },
  { value: 51538, label: 'SpeedArt' },
  { value: 51949, label: 'Sportequipe' },
  { value: 16377, label: 'Spyker' },
  { value: 66, label: 'SsangYong' },
  { value: 51974, label: 'Stormborn' },
  { value: 51795, label: 'StreetScooter' },
  { value: 51833, label: 'Studebaker' },
  { value: 67, label: 'Subaru' },
  { value: 51748, label: 'Sunbeam' },
  { value: 68, label: 'Suzuki' },
  { value: 51749, label: 'SWM' },
  { value: 51551, label: 'Talbot' },
  { value: 16404, label: 'Tasso' },
  { value: 16327, label: 'Tata' },
  { value: 51557, label: 'Tazzari EV' },
  { value: 51535, label: 'TECHART' },
  { value: 51520, label: 'Tesla' },
  { value: 51950, label: 'Togg' },
  { value: 16420, label: 'Town Life' },
  { value: 70, label: 'Toyota' },
  { value: 15633, label: 'Trabant' },
  { value: 16326, label: 'Trailer-Anhänger' },
  { value: 2120, label: 'Triumph' },
  { value: 16253, label: 'Trucks-Lkw' },
  { value: 71, label: 'TVR' },
  { value: 16389, label: 'UAZ' },
  { value: 51836, label: 'Vanden Plas' },
  { value: 51809, label: 'Vanderhall' },
  { value: 16385, label: 'VAZ' },
  { value: 16422, label: 'VEM' },
  { value: 51915, label: 'VinFast' },
  { value: 74, label: 'Volkswagen' },
  { value: 73, label: 'Volvo' },
  { value: 51993, label: 'Voyah' },
  { value: 16336, label: 'Wartburg' },
  { value: 51873, label: 'Weltmeister' },
  { value: 51852, label: 'Wenckstern' },
  { value: 51513, label: 'Westfield' },
  { value: 51935, label: 'Wey' },
  { value: 16351, label: 'Wiesmann' },
  { value: 51869, label: 'XBus' },
  { value: 51860, label: 'XEV' },
  { value: 51940, label: 'Xpeng' },
  { value: 16408, label: 'Zastava' },
  { value: 16394, label: 'ZAZ' },
  { value: 51964, label: 'Zeekr' },
  { value: 51798, label: 'Zhidou' },
  { value: 51807, label: 'Zotye' },
  { value: 16328, label: 'Sonstige' },
];

const models = Object.fromEntries(
  makes.map((make) => [
    make.value,
    [
      { value: `${make.value}-model-1`, label: `${make.label} | Model 1` },
      { value: `${make.value}-model-2`, label: `${make.label} | Model 2` },
    ],
  ])
);

const bodyTypes = [
  { value: 0, label: 'Bitte auswählen' },
  { value: 2, label: 'Cabrio' },
  { value: 3, label: 'Coupé' },
  { value: 1, label: 'Kleinwagen' },
  { value: 5, label: 'Kombi' },
  { value: 6, label: 'Limousine' },
  { value: 4, label: 'SUV/Geländewagen/Pickup' },
  { value: 13, label: 'Transporter' },
  { value: 12, label: 'Van/Kleinbus' },
  { value: 7, label: 'Sonstige' },
];

const bodyColors = [
  { value: '1', label: 'Beige' },
  { value: '2', label: 'Blau' },
  { value: '3', label: 'Braun' },
  { value: '4', label: 'Bronze' },
  { value: '5', label: 'Gelb' },
  { value: '16', label: 'Gold' },
  { value: '6', label: 'Grau' },
  { value: '7', label: 'Grün' },
  { value: '15', label: 'Orange' },
  { value: '10', label: 'Rot' },
  { value: '11', label: 'Schwarz' },
  { value: '12', label: 'Silber' },
  { value: '13', label: 'Violett' },
  { value: '14', label: 'Weiß' },
];

const upholsteryOptions = [
  { value: 'AL', label: 'Alcantara' },
  { value: 'CL', label: 'Stoff' },
  { value: 'PL', label: 'Teilleder' },
  { value: 'LE', label: 'Leder' },
  { value: 'VL', label: 'Velours' },
  { value: 'SO', label: 'Sonstige' },
];

const interiorColorOptions = [
  { value: '1', label: 'Beige' },
  { value: '2', label: 'Blau' },
  { value: '3', label: 'Braun' },
  { value: '4', label: 'Bronze' },
  { value: '5', label: 'Gelb' },
  { value: '16', label: 'Gold' },
  { value: '6', label: 'Grau' },
  { value: '7', label: 'Grün' },
  { value: '15', label: 'Orange' },
  { value: '10', label: 'Rot' },
  { value: '11', label: 'Schwarz' },
  { value: '12', label: 'Silber' },
  { value: '13', label: 'Violett' },
  { value: '14', label: 'Weiß' },
];

const vehicleOfferTypeOptions = [
  { value: 'U', label: 'Gebraucht' },
  { value: 'O', label: 'Oldtimer' },
];

const driveTypeOptions = [
  { value: '0', label: 'Bitte auswählen' },
  { value: '4', label: 'Allrad' },
  { value: 'F', label: 'Front' },
  { value: 'R', label: 'Heck' },
];

const transmissionOptions = [
  { value: '0', label: 'Bitte auswählen' },
  { value: 'A', label: 'Automatik' },
  { value: 'M', label: 'Schaltgetriebe' },
  { value: 'S', label: 'Halbautomatik' },
];

const fuelTypeOptions = [
  { value: '0', label: 'Bitte auswählen' },
  { value: 'B', label: 'Benzin' },
  { value: 'D', label: 'Diesel' },
  { value: 'L', label: 'Autogas (LPG)' },
  { value: 'C', label: 'Erdgas (CNG)' },
  { value: '2', label: 'Elektro/Benzin' },
  { value: '3', label: 'Elektro/Diesel' },
  { value: 'M', label: 'Ethanol' },
  { value: 'E', label: 'Elektro' },
  { value: 'H', label: 'Wasserstoff' },
  { value: 'O', label: 'Sonstige' },
];

const co2ClassOptions = [
  { value: '0', label: 'Bitte auswählen' },
  { value: '10', label: 'A' },
  { value: '20', label: 'B' },
  { value: '30', label: 'C' },
  { value: '40', label: 'D' },
  { value: '50', label: 'E' },
  { value: '60', label: 'F' },
];

const phoneCountryCodes = [
  { value: 'USA', label: '+1' },
  { value: 'GR', label: '+30' },
  { value: 'nl-NL', label: '+31' },
  { value: 'nl-BE', label: '+32' },
  { value: 'fr-FR', label: '+33' },
  { value: 'es-ES', label: '+34' },
  { value: 'P', label: '+351' },
  { value: 'fr-LU', label: '+352' },
  { value: 'IRL', label: '+353' },
  { value: 'IS', label: '+354' },
  { value: 'AL', label: '+355' },
  { value: 'M', label: '+356' },
  { value: 'FIN', label: '+358' },
  { value: 'BG', label: '+359' },
  { value: 'HU', label: '+36' },
  { value: 'LT', label: '+370' },
  { value: 'LV', label: '+371' },
  { value: 'EST', label: '+372' },
  { value: 'MD', label: '+373' },
  { value: 'BY', label: '+375' },
  { value: 'AND', label: '+376' },
  { value: 'MC', label: '+377' },
  { value: 'RSM', label: '+378' },
  { value: 'V', label: '+379' },
  { value: 'UA', label: '+380' },
  { value: 'RS', label: '+381' },
  { value: 'ME', label: '+382' },
  { value: 'HR', label: '+385' },
  { value: 'SLO', label: '+386' },
  { value: 'BIH', label: '+387' },
  { value: 'MK', label: '+389' },
  { value: 'it-IT', label: '+39' },
  { value: 'RO', label: '+40' },
  { value: 'CH', label: '+41' },
  { value: 'CZ', label: '+420' },
  { value: 'SK', label: '+421' },
  { value: 'LI', label: '+423' },
  { value: 'de-AT', label: '+43' },
  { value: 'UK', label: '+44' },
  { value: 'DK', label: '+45' },
  { value: 'S', label: '+46' },
  { value: 'N', label: '+47' },
  { value: 'PL', label: '+48' },
  { value: 'de-DE', label: '+49' },
  { value: 'MEX', label: '+52' },
  { value: 'BR', label: '+55' },
  { value: 'RUS', label: '+7' },
  { value: 'TR', label: '+90' },
];

export {
  bodyColors,
  bodyTypes,
  co2ClassOptions,
  driveTypeOptions,
  fuelTypeOptions,
  interiorColorOptions,
  makes,
  models,
  phoneCountryCodes,
  transmissionOptions,
  upholsteryOptions,
  vehicleOfferTypeOptions,
};
