import { z } from 'zod';

type FormFields = z.infer<typeof schema>;

const schema = z.object({
  vehicleData: z.object({
    make: z.string().min(1),
    model: z.string().min(1),
    modelVersion: z.string().min(1),
  }),
  characteristics: z.object({
    bodyType: z.string().min(1),
    seats: z.number().int(),
    doors: z.number().int(),
    color: z.string(),
    metallic: z.boolean(),
    upholstery: z.string(),
    interiorColor: z.string(),
  }),
  condition: z.object({
    vehicleOfferType: z.string(),
    mileage: z.number().int(),
    firstRegistrationMonth: z.string(),
    firstRegistrationYear: z.string(),
    owners: z.number().int(),
    deliveryDay: z.string(),
    deliveryDate: z.string(),
    fullServiceHistory: z.boolean(),
    nonSmoking: z.boolean(),
    nextInspectionMonth: z.string(),
    nextInspectionYear: z.string(),
    lastTechnicalServiceMonth: z.string(),
    lastTechnicalServiceYear: z.string(),
    lastCamBeltServiceMonth: z.string(),
    lastCamBeltServiceYear: z.string(),
    damagedVehicle: z.boolean(),
    accidentVehicle: z.boolean(),
    roadWorthiness: z.boolean(),
  }),
  equipment: z.object({
    airbags: z.object({
      rearAirbag: z.boolean(),
      passengerAirbag: z.boolean(),
      driverAirbag: z.boolean(),
      headAirbag: z.boolean(),
      sideAirbag: z.boolean(),
    }),
    assistanceSystems: z.object({
      distanceWarning: z.boolean(),
      emergencyBrakeAssist: z.boolean(),
      hillStartAssist: z.boolean(),
      laneKeepingAssist: z.boolean(),
      blindSpotAssist: z.boolean(),
      highBeamAssist: z.boolean(),
      trafficSignRecognition: z.boolean(),
      nightVisionAssist: z.boolean(),
    }),
    parkingAssist: z.object({
      camera360: z.boolean(),
      frontSensors: z.boolean(),
      rearSensors: z.boolean(),
      selfSteeringSystem: z.boolean(),
      parkingCamera: z.boolean(),
    }),
    extras: z.object({
      allWeatherTires: z.boolean(),
      punctureKit: z.boolean(),
      alloyWheels: z.boolean(),
      smokerPackage: z.boolean(),
      ambientLighting: z.boolean(),
      towBar: z.boolean(),
      rangeExtender: z.boolean(),
      batteryCertificate: z.boolean(),
      spareWheel: z.boolean(),
      wheelchairAccessible: z.boolean(),
      headlightCleaning: z.boolean(),
      bidirectionalCharging: z.boolean(),
      rearSeatHeating: z.boolean(),
    }),
    climateControl: z.object({
      twoZoneClimateControl: z.boolean(),
      airConditioning: z.boolean(),
      threeZoneClimateControl: z.boolean(),
      automaticClimateControl: z.boolean(),
      fourZoneClimateControl: z.boolean(),
    }),
    comfort: z.object({
      armrest: z.boolean(),
      panoramicRoof: z.boolean(),
      heatedWindshield: z.boolean(),
      rainSensor: z.boolean(),
      heatedSteeringWheel: z.boolean(),
      paddleShifters: z.boolean(),
      electricWindows: z.boolean(),
      sunroof: z.boolean(),
      electricTailgate: z.boolean(),
      slidingDoor: z.boolean(),
      electricSideMirrors: z.boolean(),
      headUpDisplay: z.boolean(),
      leatherSteeringWheel: z.boolean(),
      powerSteering: z.boolean(),
      lightSensor: z.boolean(),
      parkingHeater: z.boolean(),
      airSuspension: z.boolean(),
      startStopSystem: z.boolean(),
    }),
    lighting: z.object({
      biXenonHeadlights: z.boolean(),
      lightSensor: z.boolean(),
      glareFreeHighBeam: z.boolean(),
      fogLights: z.boolean(),
      corneringLights: z.boolean(),
      daytimeRunningLights: z.boolean(),
      ledHeadlights: z.boolean(),
      fullLedHeadlights: z.boolean(),
      ledDaytimeRunningLights: z.boolean(),
      xenonHeadlights: z.boolean(),
      laserLights: z.boolean(),
    }),
    safety: z.object({
      abs: z.boolean(),
      emergencyCallSystem: z.boolean(),
      alarmSystem: z.boolean(),
      tirePressureMonitoring: z.boolean(),
      esp: z.boolean(),
      tractionControl: z.boolean(),
      isofix: z.boolean(),
      immobilizer: z.boolean(),
      fatigueWarningSystem: z.boolean(),
    }),
    seats: z.object({
      electricSeats: z.boolean(),
      heatedSeats: z.boolean(),
      lumbarSupport: z.boolean(),
      sportSeats: z.boolean(),
      massageSeats: z.boolean(),
      foldablePassengerSeat: z.boolean(),
      ventilatedSeats: z.boolean(),
      splitRearSeat: z.boolean(),
    }),
    cruiseControl: z.object({
      adaptiveCruiseControl: z.boolean(),
      cruiseControl: z.boolean(),
    }),
    entertainment: z.object({
      androidAuto: z.boolean(),
      voiceControl: z.boolean(),
      appleCarPlay: z.boolean(),
      tv: z.boolean(),
      dabRadio: z.boolean(),
      touchscreen: z.boolean(),
      wirelessCharging: z.boolean(),
      usb: z.boolean(),
      integratedMusicStreaming: z.boolean(),
      digitalInstrumentCluster: z.boolean(),
      soundSystem: z.boolean(),
      wifiHotspot: z.boolean(),
    }),
    media: z.object({
      bluetooth: z.boolean(),
      mp3: z.boolean(),
      onboardComputer: z.boolean(),
      multifunctionSteeringWheel: z.boolean(),
      cd: z.boolean(),
      navigationSystem: z.boolean(),
      handsFreeSystem: z.boolean(),
      radio: z.boolean(),
    }),
    centralLocking: z.object({
      keylessCentralLocking: z.boolean(),
      remoteCentralLocking: z.boolean(),
      centralLocking: z.boolean(),
    }),
  }),
  motor: z.object({
    driveType: z.string(),
    transmission: z.string(),
    powerKW: z.number().int(),
    powerHP: z.number().int(),
    gears: z.number().int(),
    cylinders: z.number().int(),
    engineCapacity: z.number(),
    emptyWeight: z.number(),
  }),
  fuel: z.object({
    fuelType: z.string().min(1),
    primaryFuelType: z.string(),
    environmentalProtocol: z.string(),
    isPluginHybrid: z.boolean(),
    consumptionCombined: z.number(),
    wltpConsumptionCombined: z.number(),
    co2Emissions: z.number(),
    wltpCo2EmissionsCombined: z.number(),
    efficiencyClass: z.string(),
    wltpCo2Class: z.string(),
    pollutionClass: z.string(),
    emissionSticker: z.string(),
    sootParticles: z.boolean(),
  }),
  price: z.object({
    amount: z.number().min(1),
    negotiable: z.boolean(),
    taxDeductible: z.boolean(),
  }),
  contactInformation: z.object({
    postalCode: z.string().min(1),
    city: z.string().min(1),
    phoneCountryCode: z.string(),
    phoneAreaCode: z.string(),
    phoneSubscriberNumber: z.string(),
    hidePhoneNumber: z.boolean(),
  }),
  photos: z.object({
    images: z.array(z.string()),
  }),
  description: z.object({
    text: z.string(),
  }),
  financingOffer: z.object({
    price: z.number().min(1),
    netPrice: z.number(),
    taxDeductible: z.boolean(),
    negotiable: z.boolean(),
    vatRate: z.number(),
    duration: z.number().int(),
    monthlyRate: z.number(),
    annualPercentageRate: z.number(),
    initialPayment: z.number(),
    endingRate: z.number(),
  }),
});

export { schema, type FormFields };
