import { z } from 'zod';

type FormFields = z.infer<typeof schema>;

const schema = z.object({
  vehicleData: z.object({
    make: z.string().min(1),
    model: z.string().min(1),
    modelVersion: z.string().min(1),
  }),
  characteristics: z.object({
    bodyType: z.string().optional(),
    seats: z.number().int().optional(),
    doors: z.number().int().optional(),
    color: z.string().optional(),
    metallic: z.boolean().optional(),
    upholstery: z.string().optional(),
    interiorColor: z.string().optional(),
  }),
  condition: z.object({
    vehicleOfferType: z.string().optional(),
    mileage: z.number().int().optional(),
    firstRegistrationMonth: z.string().optional(),
    firstRegistrationYear: z.string().optional(),
    owners: z.number().int().optional(),
    deliveryDay: z.string().optional(),
    deliveryDate: z.string().optional(),
    fullServiceHistory: z.boolean().optional(),
    nonSmoking: z.boolean().optional(),
    nextInspectionMonth: z.string().optional(),
    nextInspectionYear: z.string().optional(),
    lastTechnicalServiceMonth: z.string().optional(),
    lastTechnicalServiceYear: z.string().optional(),
    lastCamBeltServiceMonth: z.string().optional(),
    lastCamBeltServiceYear: z.string().optional(),
    damagedVehicle: z.boolean().optional(),
    accidentVehicle: z.boolean().optional(),
    roadWorthiness: z.boolean().optional(),
  }),
  equipment: z.object({
    airbags: z.object({
      rearAirbag: z.boolean().optional(),
      passengerAirbag: z.boolean().optional(),
      driverAirbag: z.boolean().optional(),
      headAirbag: z.boolean().optional(),
      sideAirbag: z.boolean().optional(),
    }),
    assistanceSystems: z.object({
      distanceWarning: z.boolean().optional(),
      emergencyBrakeAssist: z.boolean().optional(),
      hillStartAssist: z.boolean().optional(),
      laneKeepingAssist: z.boolean().optional(),
      blindSpotAssist: z.boolean().optional(),
      highBeamAssist: z.boolean().optional(),
      trafficSignRecognition: z.boolean().optional(),
      nightVisionAssist: z.boolean().optional(),
    }),
    parkingAssist: z.object({
      camera360: z.boolean().optional(),
      frontSensors: z.boolean().optional(),
      rearSensors: z.boolean().optional(),
      selfSteeringSystem: z.boolean().optional(),
      parkingCamera: z.boolean().optional(),
    }),
    extras: z.object({
      allWeatherTires: z.boolean().optional(),
      punctureKit: z.boolean().optional(),
      alloyWheels: z.boolean().optional(),
      smokerPackage: z.boolean().optional(),
      ambientLighting: z.boolean().optional(),
      towBar: z.boolean().optional(),
      rangeExtender: z.boolean().optional(),
      batteryCertificate: z.boolean().optional(),
      spareWheel: z.boolean().optional(),
      wheelchairAccessible: z.boolean().optional(),
      headlightCleaning: z.boolean().optional(),
      bidirectionalCharging: z.boolean().optional(),
      rearSeatHeating: z.boolean().optional(),
    }),
    climateControl: z.object({
      twoZoneClimateControl: z.boolean().optional(),
      airConditioning: z.boolean().optional(),
      threeZoneClimateControl: z.boolean().optional(),
      automaticClimateControl: z.boolean().optional(),
      fourZoneClimateControl: z.boolean().optional(),
    }),
    comfort: z.object({
      armrest: z.boolean().optional(),
      panoramicRoof: z.boolean().optional(),
      heatedWindshield: z.boolean().optional(),
      rainSensor: z.boolean().optional(),
      heatedSteeringWheel: z.boolean().optional(),
      paddleShifters: z.boolean().optional(),
      electricWindows: z.boolean().optional(),
      sunroof: z.boolean().optional(),
      electricTailgate: z.boolean().optional(),
      slidingDoor: z.boolean().optional(),
      electricSideMirrors: z.boolean().optional(),
      headUpDisplay: z.boolean().optional(),
      leatherSteeringWheel: z.boolean().optional(),
      powerSteering: z.boolean().optional(),
      lightSensor: z.boolean().optional(),
      parkingHeater: z.boolean().optional(),
      airSuspension: z.boolean().optional(),
      startStopSystem: z.boolean().optional(),
    }),
    lighting: z.object({
      biXenonHeadlights: z.boolean().optional(),
      lightSensor: z.boolean().optional(),
      glareFreeHighBeam: z.boolean().optional(),
      fogLights: z.boolean().optional(),
      corneringLights: z.boolean().optional(),
      daytimeRunningLights: z.boolean().optional(),
      ledHeadlights: z.boolean().optional(),
      fullLedHeadlights: z.boolean().optional(),
      ledDaytimeRunningLights: z.boolean().optional(),
      xenonHeadlights: z.boolean().optional(),
      laserLights: z.boolean().optional(),
    }),
    safety: z.object({
      abs: z.boolean().optional(),
      emergencyCallSystem: z.boolean().optional(),
      alarmSystem: z.boolean().optional(),
      tirePressureMonitoring: z.boolean().optional(),
      esp: z.boolean().optional(),
      tractionControl: z.boolean().optional(),
      isofix: z.boolean().optional(),
      immobilizer: z.boolean().optional(),
      fatigueWarningSystem: z.boolean().optional(),
    }),
    seats: z.object({
      electricSeats: z.boolean().optional(),
      heatedSeats: z.boolean().optional(),
      lumbarSupport: z.boolean().optional(),
      sportSeats: z.boolean().optional(),
      massageSeats: z.boolean().optional(),
      foldablePassengerSeat: z.boolean().optional(),
      ventilatedSeats: z.boolean().optional(),
      splitRearSeat: z.boolean().optional(),
    }),
    cruiseControl: z.object({
      adaptiveCruiseControl: z.boolean().optional(),
      cruiseControl: z.boolean().optional(),
    }),
    entertainment: z.object({
      androidAuto: z.boolean().optional(),
      voiceControl: z.boolean().optional(),
      appleCarPlay: z.boolean().optional(),
      tv: z.boolean().optional(),
      dabRadio: z.boolean().optional(),
      touchscreen: z.boolean().optional(),
      wirelessCharging: z.boolean().optional(),
      usb: z.boolean().optional(),
      integratedMusicStreaming: z.boolean().optional(),
      digitalInstrumentCluster: z.boolean().optional(),
      soundSystem: z.boolean().optional(),
      wifiHotspot: z.boolean().optional(),
    }),
    media: z.object({
      bluetooth: z.boolean().optional(),
      mp3: z.boolean().optional(),
      onboardComputer: z.boolean().optional(),
      multifunctionSteeringWheel: z.boolean().optional(),
      cd: z.boolean().optional(),
      navigationSystem: z.boolean().optional(),
      handsFreeSystem: z.boolean().optional(),
      radio: z.boolean().optional(),
    }),
    centralLocking: z.object({
      keylessCentralLocking: z.boolean().optional(),
      remoteCentralLocking: z.boolean().optional(),
      centralLocking: z.boolean().optional(),
    }),
  }),
  motor: z.object({
    driveType: z.string().optional(),
    transmission: z.string().optional(),
    powerKW: z.number().int().optional(),
    powerHP: z.number().int().optional(),
    gears: z.number().int().optional(),
    cylinders: z.number().int().optional(),
    engineCapacity: z.number().optional(),
    emptyWeight: z.number().optional(),
  }),
  fuel: z.object({
    fuelType: z.string().min(1),
    primaryFuelType: z.string().optional(),
    environmentalProtocol: z.string().optional(),
    isPluginHybrid: z.boolean().optional(),
    consumptionCombined: z.number().optional(),
    wltpConsumptionCombined: z.number().optional(),
    co2Emissions: z.number().optional(),
    wltpCo2EmissionsCombined: z.number().optional(),
    efficiencyClass: z.string().optional(),
    wltpCo2Class: z.string().optional(),
    pollutionClass: z.string().optional(),
    emissionSticker: z.string().optional(),
    sootParticles: z.boolean().optional(),
  }),
  price: z.object({
    amount: z.number().min(1),
    negotiable: z.boolean().optional(),
    taxDeductible: z.boolean().optional(),
  }),
  contactInformation: z.object({
    postalCode: z.string().min(1),
    city: z.string().min(1),
    phoneCountryCode: z.string().optional(),
    phoneAreaCode: z.string().optional(),
    phoneSubscriberNumber: z.string().optional(),
    hidePhoneNumber: z.boolean().optional(),
  }),
  photos: z.object({
    images: z.array(z.string()).optional(),
  }),
  description: z.object({
    text: z.string().optional(),
  }),
  financingOffer: z
    .object({
      price: z.number().min(1).optional(),
      netPrice: z.number().optional(),
      taxDeductible: z.boolean().optional(),
      negotiable: z.boolean().optional(),
      vatRate: z.number().optional(),
      duration: z.number().int().optional(),
      monthlyRate: z.number().optional(),
      annualPercentageRate: z.number().optional(),
      initialPayment: z.number().optional(),
      endingRate: z.number().optional(),
    })
    .optional(),
});

export { schema, type FormFields };
